# Machine Learning

### Importing important modules and libraries

In [118]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split

### Loading dataset

In [119]:
data = load_diabetes()

### Checking the data attributes

In [120]:
dir(data)

['DESCR',
 'data',
 'data_filename',
 'data_module',
 'feature_names',
 'frame',
 'target',
 'target_filename']

### Data Description

In [121]:
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

### Getting the features names

In [122]:
data.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

### Getting the first data

In [123]:
data.data[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613])

### Getting the first target variable

In [124]:
data.target[0]

151.0

In [125]:
data.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

### Creating Pandas Dataframe

In [126]:
df = pd.DataFrame(data.data, columns=data.feature_names)

### Checking first 50 datas

In [127]:
df.head(50)

age       sex       bmi        bp        s1        s2        s3  \
0   0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1  -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2   0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3  -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4   0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
5  -0.092695 -0.044642 -0.040696 -0.019442 -0.068991 -0.079288  0.041277   
6  -0.045472  0.050680 -0.047163 -0.015999 -0.040096 -0.024800  0.000779   
7   0.063504  0.050680 -0.001895  0.066629  0.090620  0.108914  0.022869   
8   0.041708  0.050680  0.061696 -0.040099 -0.013953  0.006202 -0.028674   
9  -0.070900 -0.044642  0.039062 -0.033213 -0.012577 -0.034508 -0.024993   
10 -0.096328 -0.044642 -0.083808  0.008101 -0.103389 -0.090561 -0.013948   
11  0.027178  0.050680  0.017506 -0.033213 -0.007073  0.045972 -0.065491   
12  0.016281 -0.044642 -0.028840 -0.009113 -0.004321 -0.009769  0.044958   
13  0.005383  0.050680 -0.001895  0.008101 -0.004321 -0.015719 -0.002903   
14  0.045341 -0.044642 -0.025607 -0.012556  0.017694 -0.000061  0.081775   
15 -0.052738  0.050680 -0.018062  0.080401  0.089244  0.107662 -0.039719   
16 -0.005515 -0.044642  0.042296  0.049415  0.024574 -0.023861  0.074412   
17  0.070769  0.050680  0.012117  0.056301  0.034206  0.049416 -0.039719   
18 -0.038207 -0.044642 -0.010517 -0.036656 -0.037344 -0.019476 -0.028674   
19 -0.027310 -0.044642 -0.018062 -0.040099 -0.002945 -0.011335  0.037595   
20 -0.049105 -0.044642 -0.056863 -0.043542 -0.045599 -0.043276  0.000779   
21 -0.085430  0.050680 -0.022373  0.001215 -0.037344 -0.026366  0.015505   
22 -0.085430 -0.044642 -0.004050 -0.009113 -0.002945  0.007767  0.022869   
23  0.045341  0.050680  0.060618  0.031065  0.028702 -0.047347 -0.054446   
24 -0.063635 -0.044642  0.035829 -0.022885 -0.030464 -0.018850 -0.006584   
25 -0.067268  0.050680 -0.012673 -0.040099 -0.015328  0.004636 -0.058127   
26 -0.107226 -0.044642 -0.077342 -0.026328 -0.089630 -0.096198  0.026550   
27 -0.023677 -0.044642  0.059541 -0.040099 -0.042848 -0.043589  0.011824   
28  0.052606 -0.044642 -0.021295 -0.074527 -0.040096 -0.037639 -0.006584   
29  0.067136  0.050680 -0.006206  0.063187 -0.042848 -0.095885  0.052322   
30 -0.060003 -0.044642  0.044451 -0.019442 -0.009825 -0.007577  0.022869   
31 -0.023677 -0.044642 -0.065486 -0.081413 -0.038720 -0.053610  0.059685   
32  0.034443  0.050680  0.125287  0.028758 -0.053855 -0.012900 -0.102307   
33  0.030811 -0.044642 -0.050396 -0.002228 -0.044223 -0.089935  0.118591   
34  0.016281 -0.044642 -0.063330 -0.057313 -0.057983 -0.048912  0.008142   
35  0.048974  0.050680 -0.030996 -0.049291  0.049341 -0.004132  0.133318   
36  0.012648 -0.044642  0.022895  0.052858  0.008063 -0.028558  0.037595   
37 -0.009147 -0.044642  0.011039 -0.057313 -0.024960 -0.042963  0.030232   
38 -0.001882  0.050680  0.071397  0.097615  0.087868  0.075407 -0.021311   
39 -0.001882  0.050680  0.014272 -0.074527  0.002559  0.006202 -0.013948   
40  0.005383  0.050680 -0.008362  0.021872  0.054845  0.073215 -0.024993   
41 -0.099961 -0.044642 -0.067641 -0.108956 -0.074494 -0.072712  0.015505   
42 -0.060003  0.050680 -0.010517 -0.014863 -0.049727 -0.023547 -0.058127   
43  0.019913 -0.044642 -0.023451 -0.071085  0.020446 -0.010082  0.118591   
44  0.045341  0.050680  0.068163  0.008101 -0.016704  0.004636 -0.076536   
45  0.027178  0.050680 -0.035307  0.032201 -0.011201  0.001504 -0.010266   
46 -0.056370 -0.044642 -0.011595 -0.033213 -0.046975 -0.047660  0.004460   
47 -0.078165 -0.044642 -0.073030 -0.057313 -0.084126 -0.074277 -0.024993   
48  0.067136  0.050680 -0.041774  0.011544  0.002559  0.005889  0.041277   
49 -0.041840  0.050680  0.014272 -0.005670 -0.012577  0.006202 -0.072854   

          s4        s5        s6  
0  -0.002592  0.019907 -0.017646  
1  -0.039493 -0.068332 -0.092204  
2  -0.002592  0.002861 -0.0

### Checking first 5 datas

In [128]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

### Appending data target to the Dataframe

In [129]:
df['target'] = data.target

### Checking the first 5 datas

In [130]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

### Shape of data

In [131]:
df.shape

(442, 11)

### Data Description

In [132]:
df.describe()

age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -2.511817e-19  1.230790e-17 -2.245564e-16 -4.797570e-17 -1.381499e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123988e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665608e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670422e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564379e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320436e-01  1.539137e-01   

                 s2            s3            s4            s5            s6  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean   3.918434e-17 -5.777179e-18 -9.042540e-18  9.293722e-17  1.130318e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260971e-01 -1.377672e-01   
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324559e-02 -3.317903e-02   
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947171e-03 -1.077698e-03   
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243232e-02  2.791705e-02   
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335973e-01  1.356118e-01   

           target  
count  442.000000  
mean   152.133484  
std     77.093005  
min     25.000000  
25%     87.000000  
50%    140.500000  
75%    211.500000  
max    346.000000

### Data Information

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
 10  target  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB


### Data Correlation

In [134]:
df.corr()

age       sex       bmi        bp        s1        s2        s3  \
age     1.000000  0.173737  0.185085  0.335428  0.260061  0.219243 -0.075181   
sex     0.173737  1.000000  0.088161  0.241010  0.035277  0.142637 -0.379090   
bmi     0.185085  0.088161  1.000000  0.395411  0.249777  0.261170 -0.366811   
bp      0.335428  0.241010  0.395411  1.000000  0.242464  0.185548 -0.178762   
s1      0.260061  0.035277  0.249777  0.242464  1.000000  0.896663  0.051519   
s2      0.219243  0.142637  0.261170  0.185548  0.896663  1.000000 -0.196455   
s3     -0.075181 -0.379090 -0.366811 -0.178762  0.051519 -0.196455  1.000000   
s4      0.203841  0.332115  0.413807  0.257650  0.542207  0.659817 -0.738493   
s5      0.270774  0.149916  0.446157  0.393480  0.515503  0.318357 -0.398577   
s6      0.301731  0.208133  0.388680  0.390430  0.325717  0.290600 -0.273697   
target  0.187889  0.043062  0.586450  0.441482  0.212022  0.174054 -0.394789   

              s4        s5        s6    target  
age     0.203841  0.270774  0.301731  0.187889  
sex     0.332115  0.149916  0.208133  0.043062  
bmi     0.413807  0.446157  0.388680  0.586450  
bp      0.257650  0.393480  0.390430  0.441482  
s1      0.542207  0.515503  0.325717  0.212022  
s2      0.659817  0.318357  0.290600  0.174054  
s3     -0.738493 -0.398577 -0.273697 -0.394789  
s4      1.000000  0.617859  0.417212  0.430453  
s5      0.617859  1.000000  0.464669  0.565883  
s6      0.417212  0.464669  1.000000  0.382483  
target  0.430453  0.565883  0.382483  1.000000

### Checking correlation from highest to lowest on the basis of bmi and bp column

In [135]:
df.corr()['bmi'].sort_values(ascending=False)

bmi       1.000000
target    0.586450
s5        0.446157
s4        0.413807
bp        0.395411
s6        0.388680
s2        0.261170
s1        0.249777
age       0.185085
sex       0.088161
s3       -0.366811
Name: bmi, dtype: float64

In [136]:
df.corr()['bp'].sort_values(ascending=False)

bp        1.000000
target    0.441482
bmi       0.395411
s5        0.393480
s6        0.390430
age       0.335428
s4        0.257650
s1        0.242464
sex       0.241010
s2        0.185548
s3       -0.178762
Name: bp, dtype: float64

### Splitting data into X and y variables

In [137]:
X = df.drop(['target'], axis=1)
y = df['target']

### Checking X and y 

In [138]:
X.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

In [139]:
y.head()

0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
Name: target, dtype: float64

### Splitting data into Training and Testing dataset

In [140]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

### Checking length of both Training and Testing set

In [141]:
len(X_train)

331

In [142]:
len(X_test)

111

# MACHINE LEARNING

In [143]:
kf = StratifiedKFold(n_splits=5)

In [144]:
kf

StratifiedKFold(n_splits=5, random_state=None, shuffle=False)

In [145]:
lr = cross_val_score(LogisticRegression(), X, y, cv=kf)
lr

C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.01123596, 0.01123596, 0.01136364, 0.01136364, 0.01136364])

In [149]:
svm = cross_val_score(SVC(), X, y, cv=kf)
svm

C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.01123596, 0.01123596, 0.02272727, 0.02272727, 0.02272727])

In [150]:
rm = cross_val_score(RandomForestClassifier(),X, y, cv=kf)
rm

C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.02247191, 0.02247191, 0.02272727, 0.        , 0.01136364])